spring.application.name=spring-learn
# Server Configuration - Change port to 8083 as per requirement
server.port=8090

# Logging Configuration
logging.level.com.cognizant=DEBUG
logging.level.org.springframework=INFO

server.servlet.context-path=/spring-learn
